typedef enum eWeaponType
{
	WEAPON_UNARMED, //Hand
	WEAPON_BASEBALLBAT, //Baseball Bat
	WEAPON_POOLCUE, //Poolcue
	WEAPON_KNIFE, //Knife
	WEAPON_GRENADE, //Grenade
	WEAPON_MOLOTOV, //Molotov
	WEAPON_ROCKET, //RPG Rocket
	WEAPON_PISTOL, //Glock
	WEAPON_UNUSED0, //it was silenced pistol but unused
	WEAPON_DEAGLE, //Desert Eagle
	WEAPON_SHOTGUN, //Ithaca Model 37
	WEAPON_BARETTA, //Remington 1100 Tac 4
	WEAPON_MICRO_UZI, //IMI UZI
	WEAPON_MP5, //MP5
	WEAPON_AK47, //AK47
	WEAPON_M4, //M4A1
	WEAPON_SNIPERRIFLE, //Remington 700
	WEAPON_M40A1, //H&K PSG1
	WEAPON_RLAUNCHER, //Rocket Launcher 
	WEAPON_FTHROWER, //Flamethrower - can make usable by installing a mod
	WEAPON_MINIGUN, //Minigun (Heli and Handheld both)
	WEAPON_EPISODIC_1, //Grenade Launcher TLAD/TBOGT
	WEAPON_EPISODIC_2, //Sweeper Shotgun TLAD
	WEAPON_EPISODIC_3,
	WEAPON_EPISODIC_4, //POOL CUE TLAD
	WEAPON_EPISODIC_5, //Grenade From the Grenade Launcher TLAD/TBOGT
	WEAPON_EPISODIC_6, //Sawnoff Shotgun TLAD
	WEAPON_EPISODIC_7, //Automatic 9mm TLAD
	WEAPON_EPISODIC_8, //Pipe Bomb TLAD
	WEAPON_EPISODIC_9, //.44 Pistol TBOGT
	WEAPON_EPISODIC_10, //Explosive AA12 TBOGT
	WEAPON_EPISODIC_11, //AA12 TBOGT
	WEAPON_EPISODIC_12, //P-90 TBOGT
	WEAPON_EPISODIC_13, //Golden Uzi TBOGT
	WEAPON_EPISODIC_14, //M249 TBOGT
	WEAPON_EPISODIC_15, //Explosive Sniper TBOGT
	WEAPON_EPISODIC_16, //Sticky Bombs TBOGT
	WEAPON_EPISODIC_17, //BUZZARD (heli) rocket launcher/null TBOGT
	WEAPON_EPISODIC_18, //BUZZARD (heli) rocket for BUZZARD rocket launcher/freeze TBOGT
	WEAPON_EPISODIC_19, //BUZZARD (heli) minigun TBOGT
	WEAPON_EPISODIC_20, //APC cannon TBOGT
	WEAPON_EPISODIC_21, //Parachute TBOGT
	WEAPON_EPISODIC_22,
	WEAPON_EPISODIC_23,
	WEAPON_EPISODIC_24,
	WEAPON_CAMERA,
	WEAPON_OBJECT,
	WEAPON_WEAPONTYPE_LAST_WEAPONTYPE,
	WEAPON_ARMOUR,
	WEAPON_RAMMEDBYCAR,
	WEAPON_RUNOVERBYCAR,
	WEAPON_EXPLOSION,
	WEAPON_UZI_DRIVEBY,
	WEAPON_DROWNING,
	WEAPON_FALL,
	WEAPON_UNIDENTIFIED,
	WEAPON_ANYMELEE,
	WEAPON_ANYWEAPON,
} eWeapon;
